# Generated by Django 6.0.1 on 2026-01-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numbre',
            new_name='phone_number',
        ),
    ]
